# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='candidate',
            name='impressions_after',
            field=models.CharField(blank=True, choices=[('after_1', 'It is a no'), ('after_2', 'Rather not'), ('after_3', 'Short list'), ('after_4', 'Make an offer')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='impressions_before',
            field=models.CharField(blank=True, choices=[('before_1', 'Not okay'), ('before_2', 'Rather not'), ('before_2', 'Interesting'), ('before_3', 'We must meet')], max_length=32, null=True),
        ),
    ]
