# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20190326_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='mark_soft_skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='mark_tech_skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='soft_skills',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tech_skills',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
