# Generated by Django 2.1 on 2019-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='impressions_after',
            field=models.IntegerField(blank=True, choices=[(1, '+'), (2, '++'), (3, '+++'), (4, '++++'), (5, '++++++')], null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='impressions_before',
            field=models.IntegerField(blank=True, choices=[(1, '+'), (2, '++'), (3, '+++'), (4, '++++'), (5, '++++++')], null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='soft_skills',
            field=models.IntegerField(blank=True, choices=[(1, '+'), (2, '++'), (3, '+++'), (4, '++++'), (5, '++++++')], null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tech_skills',
            field=models.IntegerField(blank=True, choices=[(1, '+'), (2, '++'), (3, '+++'), (4, '++++'), (5, '++++++')], null=True),
        ),
    ]
